NumPy Reference :  https://numpy.org/doc/stable/user/quickstart.html

In [2]:
import numpy as np

In [3]:
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
print(arr + 5)

[ 5  6  7  8  9 10 11 12 13 14]


In [5]:
print(arr - 3)

[-3 -2 -1  0  1  2  3  4  5  6]


In [6]:
print(arr + arr )

[ 0  2  4  6  8 10 12 14 16 18]


In [7]:
print(arr * arr)

[ 0  1  4  9 16 25 36 49 64 81]


In [8]:
print(arr / arr )

[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]


/var/folders/_t/0rqjywnx1_z3rvn8xgy9yhg00000gn/T/ipykernel_90058/2234150364.py:1: RuntimeWarning: invalid value encountered in divide
  print(arr / arr )


In [9]:
print(1 / arr )

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]


/var/folders/_t/0rqjywnx1_z3rvn8xgy9yhg00000gn/T/ipykernel_90058/514354577.py:1: RuntimeWarning: divide by zero encountered in divide
  print(1 / arr )


In [10]:
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [11]:
print(np.sin(arr))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]


In [12]:
print(np.log(arr))

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/var/folders/_t/0rqjywnx1_z3rvn8xgy9yhg00000gn/T/ipykernel_90058/873111080.py:1: RuntimeWarning: divide by zero encountered in log
  print(np.log(arr))


In [14]:
print(arr.mean())
print(arr.max())
print(arr.min())


4.5
9
0


In [15]:
print(arr.var())

8.25


In [16]:
print(arr.std())

2.8722813232690143


In [17]:
print(arr.sum())

45


Playing with 2D array

In [18]:
arr2d = np.arange(0,25).reshape(5,5)
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [19]:
print(arr2d.sum())

300


In [20]:
row_sum = arr2d.sum(axis=0)  # perform operation across rows 
print(row_sum)

[50 55 60 65 70]


In [21]:
col_sum = arr2d.sum(axis=1)
print(col_sum)

[ 10  35  60  85 110]


In [22]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/225a449484e12e0535fbbac2231b426b

import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total =  account_transactions.sum()
print(account_total)

2720
