Indexing and Selection
- Grabbing a single element 
- Grabbing a slice of elements 
- Broadcasting selections
- Indexing and selection in 2-dimensions 
- Conditional Selection 

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [4]:
print(arr[8])

8


In [5]:
print(arr[1:9])

[1 2 3 4 5 6 7 8]


In [6]:
print(arr[0:5])
print(arr[1:5])

print(arr[5:])
print(arr[:5])

[0 1 2 3 4]
[1 2 3 4]
[ 5  6  7  8  9 10]
[0 1 2 3 4]


Broadcast - Unlike Python , NumPy can Broascast a value to multiple set of values 

In [8]:
arr[0:5] = 100 
print(arr)

## This is NOT possible in normal Python . Here , 100 is broadcasted to the set of values 

[100 100 100 100 100   5   6   7   8   9  10]


In [9]:
arr = np.arange(0,11)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [10]:
slice_of_arr = arr[0:5]
print(slice_of_arr)

[0 1 2 3 4]


In [11]:
slice_of_arr[:] = 99 
print(slice_of_arr)

[99 99 99 99 99]


In [13]:
print(arr)

## See the broadcasting was done to the sliced one , but it affected the original array  

[99 99 99 99 99  5  6  7  8  9 10]


In [14]:
arr_copy = arr.copy()
arr_copy[:] = 100 

In [15]:
print("Original array " ,arr)
print("Changed array",arr_copy)

Original array  [99 99 99 99 99  5  6  7  8  9 10]
Changed array [100 100 100 100 100 100 100 100 100 100 100]


Indexing

In [16]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [19]:
print(arr_2d.shape)

(3, 3)


In [20]:
print(arr_2d[0])

[ 5 10 15]


In [21]:
print(arr_2d[1][1])
print(arr_2d[1,1])

25
25


In [23]:
print(arr_2d[:2,1:])

[[10 15]
 [25 30]]


In [24]:
# Conditional selection
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
print(arr >  4)

[False False False False  True  True  True  True  True  True]


In [27]:
bool_arr = arr > 4
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [28]:
print(arr[bool_arr])

[ 5  6  7  8  9 10]


In [30]:
print(arr[arr > 4])

[ 5  6  7  8  9 10]
