In [59]:
import numpy as np

In [75]:
mylist = [1,2,3,4]
print(type(mylist))

<class 'list'>


In [76]:
myarray = np.array(mylist)
print(type(myarray))

<class 'numpy.ndarray'>


In [77]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
print(type(my_matrix))

print(np.array(my_matrix))

<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [78]:
print(np.arange(0,10,2))
print(np.arange(0,100,2))

[0 2 4 6 8]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [79]:
a   = np.zeros(50)
aa  = np.zeros((5,5))
aaa = np.zeros((2,5))

print(a)
print(aa)
print(aaa)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [80]:
b = np.ones(5)
bb = np.ones((5,5))
print(b)
print(bb)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
# Evenly spaced 
lin = np.linspace(0,10,30)
print(lin)

[ 0.          0.34482759  0.68965517  1.03448276  1.37931034  1.72413793
  2.06896552  2.4137931   2.75862069  3.10344828  3.44827586  3.79310345
  4.13793103  4.48275862  4.82758621  5.17241379  5.51724138  5.86206897
  6.20689655  6.55172414  6.89655172  7.24137931  7.5862069   7.93103448
  8.27586207  8.62068966  8.96551724  9.31034483  9.65517241 10.        ]


In [81]:
# Identity Matrix or Square Matrix
Identity = np.eye(5)
print(Identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [82]:
print(np.random.rand(1))
# Create an array of the given shape and populate it with random samples from a UNIFORM DISTRIBUTION

[0.15601864]


In [83]:
print(np.random.rand(5,2))

[[0.15599452 0.05808361]
 [0.86617615 0.60111501]
 [0.70807258 0.02058449]
 [0.96990985 0.83244264]
 [0.21233911 0.18182497]]


In [84]:
print(np.random.randn(10))

[-0.57138017 -0.92408284 -2.61254901  0.95036968  0.81644508 -1.523876
 -0.42804606 -0.74240684 -0.7033438  -2.13962066]


In [85]:
print(np.random.randn(2,3))

[[-0.62947496  0.59772047  2.55948803]
 [ 0.39423302  0.12221917 -0.51543566]]


In [86]:
print(np.random.randint(0,101,5))

[20 72 38 17  3]


In [88]:
np.random.seed(42)  ## 42 is just a arbitory choice 
print(np.random.rand(4))

[0.37454012 0.95071431 0.73199394 0.59865848]


In [74]:
arr = np.arange(0,25)

arr.reshape(5,4)
# Why this error ? 
# Because we cannot fit 25 values in a shape of (5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [89]:
arr = np.arange(0,25)
print(arr.reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
ranarr = np.random.randint(0,101,10)
print(ranarr) 


[ 14  61  61  46  61  50  54  63   2 100]


In [ ]:
ranarr.max()



100

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmax()

9

In [ ]:
ranarr.argmin()

8

In [ ]:
ranarr.dtype

dtype('int64')

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr = arr.reshape(5,5)

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])